version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://rabbitmq:5672

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/microservices
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - JWT_SECRET=secret
    depends_on:
      - mongo
      - rabbitmq
      - api-gateway

volumes:
  mongo-data:
