apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
spec:
  containers:
    - name: rabbitmq
      image: rabbitmq:3-management
      ports:
        - containerPort: 5672
        - containerPort: 15672
